### ISSUE TITLE
[Charts & Dashboards] Version history for charts and dashboards.

### ISSUE THREAD

**Issue by EBoisseauSierra** [apache-superset/superset-roadmap#155]
### Motivation

People fail. And that's ok. So people should have the right to fail… and the possibility to recover from it.
This goes for chart and dashboard building too.

So after someone modifies a chart/dashboard, it should be possible for them or someone else to revert to an earlier version of it.

This would incidentally makes ex post auditing easier (so we can easily answer “What was the version of the chart I saw last week?”).

### Proposed Functionality

We'd like to have version history for chart/dashboard, i.e. a linear set of chart/dashboard definition snapshots, that one can revert to. I'm thinking of something very similar to what exists in Google Docs.

Scope would be:

- Must have:
  - [in Edit mode] Identify when was the document last modified:<br/>
![Screenshot from 2021-02-22 14-38-36_shadow](https://user-images.githubusercontent.com/37387755/108723472-32fe6900-751c-11eb-971b-d42ac253109f.png)
  - [in Edit mode] Make possible to see a list of the different versions, alongside their author and timestamp:<br/>
![Screenshot from 2021-02-22 14-36-48_2_shadow](https://user-images.githubusercontent.com/37387755/108723481-372a8680-751c-11eb-9b41-97b6b1d280bf.png)
  - [in Edit mode] Make possible to restore an earlier version.
- Nice to have:
  - [in Edit mode] Possibility to name a version.
  - [in Edit mode] Possibility to “approve” a version (just like trusted metrics) — this could be a specific privilege that could be granted to some users only.
  - [in Edit mode] Possibility to see the changes from one version to another. (How to achieve this is still unclear to me: do we want to see the diff in the underlying JSON definition? In the GUI definition? The rendered chart/dashboard?)
  - [in Normal mode] Possibility to display version UUID (something like a footer) and/or last modified timestamp.

**Comment by junlincc** [comment]
Hi @EBoisseauSierra thank you for proposing, using the template! We received similar requests before and have thought about it(not at such detailed level though🙂) 

`[in Edit mode] Identify when was the document last modified ✅` 

The piece of info is currently available in home screen recent card/but broken🤦🏾‍♀️, and yes, agree we should have this in dashboard. 

`[in Edit mode] Make possible to see a list of the different versions, alongside their author and timestamp ✅ `

also feasible. since it's already recorded in the log. 

`[in Edit mode] Make possible to restore an earlier version.` 

we will consider this feature as part of Trash can/undo Epic.

**Comment by junlincc** [comment]
@geido @mirhi174 ^ Let's add first two in scope when we work on Dashboard.
