### ISSUE TITLE
[homepage]redesign and implement profile page

### ISSUE THREAD

**Issue by junlincc** [apache-superset/superset-roadmap#80]
Add Profile info and remove /user page

**Comment by rusackas** [comment]
This is becoming a bit more contentious as the Profile page may warrant its own view in time, so we can add additional settings/preferences and metadata there, along with the ability to edit the profile and so on.

There may still be a big value in surfacing some of this on the home page, (the avatar, at least) but there might be too much to shoehorn there over time.

**Comment by junlincc** [comment]
> This is becoming a bit more contentious as the Profile page may warrant its own view in time, so we can add additional settings/preferences and metadata there, along with the ability to edit the profile and so on.

agreed! let's keep profile edit functionalities separate from home screen. 

> 
> There may still be a big value in surfacing some of this on the home page, (the avatar, at least) but there might be too much to shoehorn there over time.

As a user, I would like to view small size avata, name, initial icon, company/team info, role/permission level, last login time on home screen.. if that's not too much of a ask... 

@zuzana-vej wdyt?

**Comment by zuzana-vej** [comment]
Our users used the profile page to view saved and created content. But that is now part of the welcome page. Is that info going to be deprecated from profile page since it is duplicate? 

What are the plans for profile page - when & why would user go to profile page?

**Welcome page:**
I think in long term, welcome page has lot of opportunity, since it's the landing page user lands on when first opening Superset (unless they have direct link to their dashboards). While the current content (recently viewed dashboards, charts etc.) is super useful here are other things that could be included (long term) on welcome page:
1. Brief user info as @junlincc  mentioned (Welcome Zuzana! and/pr user profile info somewhere in the corner  
-- Agree with: avatar, name, last login. 
-- Unsure: what "initial icon" means, if "role/permission level" is necessary - this is what could be in profile page, company/team (we don't use this concept of teams, but I agree generally if this is an option, or if a company wants to put their name or logo on the welcome page, that should be fine in general) 

2. [maybe] Section which can have some company specific customizable content (I know there are links at top right to link to documentation and file bugs, but not everyone knows that. I can imagine generally some companies might want to include few links at the top. But I can also see how for users who know everything this section could be annoying to always display. Having it collapsible could work either way. Idk how other products deal with this.

3. [maybe] What's new in Superset or New since your last login - content either same for everyone (probably easier) like new features over last 30 days, or personalized (new features since users last visit); any new features could include links to documentation or video or blog post etc. if needed. this should be collapsible too probably

between points 2 and 3, 3 would be more valuable for us, and they actually can be even combined into one section, making (2) optional part of point (3), just throwing this out there as ideas.

**Profile page:**
Should more granular details like permissions etc. be on profile page? Language settings? - right now it's top right corner, but this is something that user sets up once. It might not be necessary to have it so visibly (I often click on it by mistake when I m trying to click on ... of a chart at top right of a dashboard.)

**Comment by junlincc** [comment]
Ability to show to admin team activity

**Comment by junlincc** [comment]
have toggle thumbnail a global change in profile page
