### ISSUE TITLE
Copy/Paste to Google Sheets

### ISSUE THREAD

**Issue by yousoph** [apache-superset/superset-roadmap#99]
https://github.com/apache/incubator-superset/issues/10332

**Comment by zuzana-vej** [comment]
@yousoph just curious if this is still on roadmap

**Comment by yousoph** [comment]
@zuzana-vej yes, planning to look into whether there's a way to get the copy paste to work as expected as a first step. Not including column names yet though.

**Comment by wdepril** [comment]
Instead of copy/pasting have you thought about directly exporting it to google sheets.  We used chartio before and the chart export feature allowed export to csv/google sheets/....  Google sheets export was one of the most used features that our dashboards user used when they had to export data.

when you export it would authenticate you, create a new sheet and drop the data into the sheet.
